Remove `class << io ... end` since not threadsafe
In MRI, defining singleton methods using `class << obj... def` is not
threadsafe. To work around this issue, use an alternative syntax that is
threadsafe: `def obj.method`.

This fixes a NoMethodError that would occasionally pop up in multithreaded
usage of net-ssh: NoMethodError: undefined method `recv' for #<IO:fd 47>.